name: test examples cross-platform

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: run examples on ${{ matrix.runner.os }}
    runs-on: ${{ matrix.runner.os }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          [
            { os: ubuntu-latest, cmp: gcc-14 },
            { os: windows-latest, cmp: msvc },
            { os: macos-latest, cmp: clang, ver: "19.1.1" },
          ]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: install llvm toolchain (macos)
        if: matrix.runner.os == 'macos-latest'
        run: |
          xrepo install -y llvm ${{ matrix.runner.ver }}
          echo "LLVM_PATH=$(xrepo fetch --sdk llvm ${{ matrix.runner.ver }} | grep 'sdk:' | awk '{print $2}')" >> $GITHUB_ENV

      - name: set xmake toolchain
        run: |
          if ([ "${{ matrix.runner.os }}" == "macos-latest" ]) then
            xmake f -v --toolchain=${{ matrix.runner.cmp }} --sdk=$LLVM_PATH
          else
            xmake f -v --toolchain=${{ matrix.runner.cmp }}
          fi

      - name: build examples
        run: xmake b -v -g examples

      - name: run examples
        run: xmake r -g examples
        timeout-minutes: 2
